# Generated by Django 6.0.4 on 2026-04-26 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Удалён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('member', 'Участник')], default='member', max_length=20, verbose_name='Роль в компании')),
                ('status', models.CharField(choices=[('invited', 'Приглашён'), ('active', 'Активен'), ('declined', 'Отклонён')], default='invited', max_length=20, verbose_name='Статус')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='Присоединился')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.company', verbose_name='Компания')),
                ('invited_by', models.ForeignKey(blank=True, db_column='invited_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL, verbose_name='Пригласил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник компании',
                'verbose_name_plural': 'Участники компаний',
                'db_table': 'company_members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['owner'], name='companies_owner_i_24e005_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['deleted_at'], name='companies_deleted_530ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='companymember',
            index=models.Index(fields=['company', 'status'], name='company_mem_company_1e5fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='companymember',
            index=models.Index(fields=['user', 'status'], name='company_mem_user_id_19f469_idx'),
        ),
        migrations.AddIndex(
            model_name='companymember',
            index=models.Index(fields=['role'], name='company_mem_role_b02002_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companymember',
            unique_together={('company', 'user')},
        ),
    ]
