# Generated by Django 6.0.4 on 2026-04-08 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('done', 'Завершена'), ('cancelled', 'Отменена')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], db_index=True, default='medium', max_length=20, verbose_name='Приоритет')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дедлайн')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Оценка времени (часы)')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Фактические часы')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Удалён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task', verbose_name='Родительская задача')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='tasks_status_031d4c_idx'), models.Index(fields=['priority'], name='tasks_priorit_a9efa1_idx'), models.Index(fields=['assignee'], name='tasks_assigne_462a05_idx'), models.Index(fields=['creator'], name='tasks_creator_e587e6_idx'), models.Index(fields=['project'], name='tasks_project_f1bd77_idx'), models.Index(fields=['due_date'], name='tasks_due_dat_0359a9_idx'), models.Index(fields=['deleted_at'], name='tasks_deleted_1d9a30_idx'), models.Index(fields=['parent_task'], name='tasks_parent__ebc03e_idx')],
            },
        ),
    ]
