# Generated by Django 6.0.4 on 2026-04-26 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('core', '0002_project_company_project_projects_company_408096_idx'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['company'], name='tasks_company_a05724_idx'),
        ),
    ]
