# Generated by Django 6.0.4 on 2026-04-28 20:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_companymember_role'),
        ('tasks', '0002_task_company_task_tasks_company_a05724_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='Цвет')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status_key', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ключ статуса задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_columns', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Колонка канбана',
                'verbose_name_plural': 'Колонки канбана',
                'db_table': 'kanban_columns',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='kanban_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.kanbancolumn', verbose_name='Колонка канбана'),
        ),
    ]
