# Generated by Django 6.0.4 on 2026-05-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_channel_type_chatmessage_edited_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Назначена задача'), ('status_changed', 'Изменён статус'), ('deadline_soon', 'Скоро дедлайн'), ('task_created', 'Создана задача'), ('comment_mention', 'Упоминание в комментарии'), ('chat_mention', 'Упоминание в чате')], max_length=30),
        ),
    ]
