# Generated by Django 6.0.4 on 2026-04-08 19:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Код проекта')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершён'), ('on_hold', 'Приостановлен'), ('cancelled', 'Отменён')], default='active', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='projects_status_6303d7_idx'), models.Index(fields=['owner'], name='projects_owner_i_c299b3_idx'), models.Index(fields=['manager'], name='projects_manager_7972b6_idx'), models.Index(fields=['deadline'], name='projects_deadlin_ebe3da_idx'), models.Index(fields=['deleted_at'], name='projects_deleted_58df0e_idx')],
            },
        ),
    ]
